version: 0.0
os: linux

files:
  - source: webapp
    destination: /var/lib/webapps
  - source: cloudwatch-config.json
    destination: /opt

hooks:
  AfterInstall:
    - location: ./codedeploy/AfterInstall.sh
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/ApplicationStop.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/ApplicationStart.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: ./codedeploy/BeforeInstall.sh
      timeout: 180
      runas: ubuntu