version: 0.0
os: linux

files:
  - source: webapp
    destination: /var/lib/webapps

hooks:
  AfterInstall:
    - location: ./codedeploy/AfterInstall.sh
  ApplicationStop:
    - location: ./codedeploy/ApplicationStop.sh
  ApplicationStart:
    - location: ./codedeploy/ApplicationStart.sh
  BeforeInstall:
    - location: ./codedeploy/BeforeInstall.sh
  ValidateService:
    - location: ./codedeploy/ValidateService.sh